name: Automated Release Notes

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to generate notes for'
        required: true
        default: 'latest'

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for complete git log

      - name: Generate Release Notes
        id: release-notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          fi
          
          echo "Generating release notes for: $VERSION"
          
          # Run the release notes script
          ./scripts/generate-release-notes.sh "$VERSION" > release-notes.md
          
          # Display the generated notes
          echo "Generated release notes:"
          cat release-notes.md
          
          # Set output for use in other steps
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat release-notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release with Generated Notes
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-notes.md
          draft: false
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes-${{ github.ref_name }}
          path: release-notes.md
